apt-get update

apt-get install -y mysql-client

mysql -u $MYSQL_ENV_MYSQL_USER -p$MYSQL_ENV_MYSQL_PASSWORD -h $MYSQL_PORT_3306_TCP_ADDR -P $MYSQL_PORT_3306_TCP_PORT << EOF

# todo: call followings in code

CREATE DATABASE IF NOT EXISTS $MYSQL_ENV_MYSQL_DATABASE;
USE $MYSQL_ENV_MYSQL_DATABASE;

CREATE TABLE IF NOT EXISTS DH_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
)  DEFAULT CHARSET=UTF8;

EOF
